BASE_URL = 'https://feelinsonice-hrd.appspot.com'
STATIC_TOKEN = 'm198sOkJEn37DjqZ32lpRu76xmw288xSQ9'

DEFAULT_TIMEOUT = 15
DEFAULT_DURATION = 5

SNAP_IMAGE_DIMENSIONS = (1334, 750)

MEDIA_TYPE_UNKNOWN = -1
MEDIA_TYPE_IMAGE = 0
MEDIA_TYPE_VIDEO = 1
MEDIA_TYPE_VIDEO_WITHOUT_AUDIO = 2
